spring.application.name=social-api

# PostgreSQL - Updated to match your database
spring.datasource.url=jdbc:postgresql://localhost:5432/social_db
spring.datasource.username=social
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Scheduling
spring.task.scheduling.pool.size=5

# Logging
logging.level.com.socialapi=DEBUG


server.port=8089